apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-local
  namespace: homework
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  volumeName: pv-local