apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: homework
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      volumes:
      - name: shared-volume
        persistentVolumeClaim:
          claimName: pvc-local
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: homework
                operator: In
                values:
                - "true"
      containers:
      - name: test
        image: nginx
        volumeMounts:
        - name: shared-volume
          mountPath: /homework
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "rm /homework/index.html; touch /homework/Before_stop_$(hostname)"]
#      nodeSelector:
#        node: control