apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: standard
  hostPath:
    path: /data/pv-hostpath
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: homework
          operator: In
          values:
          - "true"