apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: homework
  labels:
    app: nginx-app
data:
  nginx.conf: |
    user nginx;
    worker_processes  auto;
    error_log   /var/log/nginx/error.log notice;
    pid         /var/run/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
        server {
          listen        8000;
          server_name   localhost;
     
          location /  {
          root      /homework;
          index     index.html index.htm;
          }
        }

        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;
    }
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: homework
  labels: 
    app: nginx-app
spec:
  type: NodePort
  ports:
    - port: 8000
  selector:
    app: nginx-app
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: homework
  labels:
    app: nginx-app
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 8000
      volumeMounts:
      - name: nginx-conf
        mountPath: /etc/nginx
      - name: shared-volume
        mountPath: /homework
      lifecycle:
        preStop:
          exec:
            command: ["/bin/sh","-c","rm /homework/index.html"]
  initContainers:
  - name: busybox
    image: busybox:latest
    command:
    - wget
    - "-O"
    - "/init/index.html"
    - http://info.cern.ch
    volumeMounts:
    - name: shared-volume 
      mountPath: /init
  volumes:
  - name: nginx-conf
    configMap:
      name: nginx-conf
  - name: shared-volume
    emptyDir: {}
